version: '3'

services:
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - mynet2
  storeDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
    - dbdata:/var/lib/mysql
    networks:
      - mynet2
  storeDBMigration:
    image: storedbmigration
    environment:
      - DATABASE_URL=storeDB
    depends_on:
      storeDB:
        condition: service_healthy
    networks:
      - mynet2
  redis:
    image: redis
    ports:
    - "6379:6379"
    networks:
      - redisnet
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=storeDB
    depends_on:
      - storeDBMigration
    networks:
      - redisnet
      - mynet2
  warehouse:
    image: warehouse
    depends_on:
      - storeDBMigration
    ports:
      - "5001:5001"
    networks:
      - redisnet
  customer:
    image: customer
    environment:
      - DATABASE_URL=storeDB
    depends_on:
      - storeDBMigration
    ports:
    - "5002:5002"
    networks:
      - mynet2
  admin:
    image: admin
    environment:
      - DATABASE_URL=storeDB
    depends_on:
      - storeDBMigration
    ports:
    - "5003:5003"
    networks:
      - mynet2



volumes:
  dbdata:

networks:
  mynet2:
  redisnet: